### ISSUE TITLE
KeyError raised when running `display_manager.py show available`

### ISSUE THREAD

**Issue by SamBaRufus** [univ-of-utah-marriott-library-apple/display_manager#10]
This issue is submitted on behalf of Rob:

> First, thanks for creating Display Manager!

> I’ve been using v1.0.1 successfully for some time, with a trio of different displays (including a MacBook Pro 15-inch’s internal display). No errors, no problems. Today, I connected up a Dell P2415Q, which is the first Retina-type external display I’ve tried. With it attached, various Display Manager commands result in traceback errors, which I’ve never gotten before with your software.

```
$ display_manager.py show available
display "main":
Traceback (most recent call last):
  File "/usr/local/bin/display_manager.py", line 1257, in <module>
    main()
  File "/usr/local/bin/display_manager.py", line 1250, in main
    commands.run()
  File "/usr/local/bin/display_manager.py", line 671, in run
    command.run()
  File "/usr/local/bin/display_manager.py", line 269, in run
    self.__handleShow()
  File "/usr/local/bin/display_manager.py", line 449, in __handleShow
    for mode in sorted(display.allModes, reverse=True):
  File "/Library/Python/2.7/site-packages/display_manager_lib.py", line 291, in allModes
    uniqueModes.remove(mode)
KeyError: <display_manager_lib.DisplayMode object at 0x1116c6ed0>
```

**Comment by SamBaRufus** [comment]
Issue is fixed in 1.0.2
