### ISSUE TITLE
GUI command

### ISSUE THREAD

**Issue by cyberbof** [univ-of-utah-marriott-library-apple/display_manager#12]
Hello,
Im nooby with Python but I can't launch gui.py (usr/local/bin/gui.py) from command line :
Traceback (most recent call last):
  File "./gui.py", line 454, in <module>
    main()
  File "./gui.py", line 450, in main
    view.start()
  File "./gui.py", line 443, in start
    self.__reloadDisplay()
  File "./gui.py", line 430, in __reloadDisplay
    self.__modeSelectionInit()
  File "./gui.py", line 226, in __modeSelectionInit
    for mode in sorted(self.display.allModes(), reverse=True):
TypeError: 'list' object is not callable

**Comment by uurazzle** [comment]
@cyberbof Sorry about issue and thanks for notify us. We are currently very busy with other projects and will not be able to get time to investigate this issue this soon, but will add it to our todo's and will troubleshoot and reply back as soon as we are able.
