### ISSUE TITLE
Can't mirror to all external displays

### ISSUE THREAD

**Issue by jross-nu** [univ-of-utah-marriott-library-apple/display_manager#15]
I'm getting the following error when executing display_manager.py mirror enable main all

Traceback (most recent call last):
  File "/usr/local/bin/display_manager.py", line 1257, in <module>
    main()
  File "/usr/local/bin/display_manager.py", line 1250, in main
    commands.run()
  File "/usr/local/bin/display_manager.py", line 682, in run
    currentMirror = display.mirrorSource
AttributeError: 'list' object has no attribute 'mirrorSource'

I can mirror to individual external displays.

**Comment by uurazzle** [comment]
@jross-nu Thanks for the feedback, we will add it to our todo's and get to it when we have the bandwidth.
